[package]
name = "router"
version = "0.0.1"
edition = "2021"

[lib]
doctest = false

[dependencies]
dex = { path = "../../lib/dex", version = "0.0.1" }
raydium-amm = { path = "../../lib/raydium-amm", version = "0.0.1" }
raydium-clmm = { path = "../../lib/raydium-clmm", version = "0.0.1" }
pump-fun = { path = "../../lib/pump-fun", version = "0.0.1" }
meteora-dlmm = { path = "../../lib/meteora-dlmm", version = "0.0.1" }
solana-program = { workspace = true }
solana-client = { workspace = true }
spl-token-2022 = { workspace = true }
arrayref = { workspace = true }
anyhow = { workspace = true }
tokio = "1.44.1"
log = "0.4.27"
base58 = "0.2.0"
env_logger = "0.9.3"

[dev-dependencies]
criterion = "0.5"
spl-token = { workspace = true }
bincode = "1.3.3"
anchor-spl = { workspace = true }
solana-sdk = { workspace = true }
futures-util = "0.3"
chrono = "0.4"

yellowstone-grpc-client = { version = "1.15.0", git = "https://github.com/blockworks-foundation/yellowstone-grpc.git", tag = "v1.15.0+solana.1.18" }
yellowstone-grpc-proto = { version = "1.14.0", git = "https://github.com/blockworks-foundation/yellowstone-grpc.git", tag = "v1.15.0+solana.1.18" }
tonic = "0.12.1"


serde = { version = "1.0", features = ["derive"] }
serde-diff = "0.4"
serde_json = "1.0"

[[bench]]
name = "test_quote_benches"
harness = false