[package]
name = "router"
version = "0.0.1"
edition = "2021"
license = "MIT"
authors = ["solana"]
build = "build.rs"


[lib]
doctest = false

[profile.bench]
debug = true
opt-level = 3 # 启用优化

[dependencies]
borsh = "^1.5"
clap = {version = "4.5.37",features = ["derive"]}
anchor-lang = { version = "0.29.0", features = ["derive"], package = "anchor-lang" }

serde.workspace = true
serde_json.workspace = true
bincode.workspace = true
dashmap = { workspace = true }
solana-program = { workspace = true }
solana-client = { workspace = true }
solana-sdk = { workspace = true }
spl-token-2022 = { workspace = true }
anyhow = { workspace = true }
base58.workspace = true
chrono.workspace = true
futures-util.workspace = true
spl-token = { workspace = true }

yellowstone-grpc-client = { workspace = true }
yellowstone-grpc-proto = { workspace = true }
solana-account-decoder = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing-appender = { workspace = true }
thiserror = "1.0.51"
num-traits = "0.2.19"
num-derive = "0.4.2"
bytemuck = { workspace = true, features = ["derive", "min_const_generics"] }
safe-transmute = "0.11.2"
burberry = { workspace = true }
eyre.workspace = true
async-stream = "0.3.6"
async-channel.workspace = true
moka.workspace = true
uint = { workspace = true }
anchor-spl = { workspace = true }
spl-associated-token-account.workspace = true
reqwest.workspace = true
arrayref = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }

num-integer = "0.1.45"
anchor-client.workspace = true
ruint.version = "1.3.0"
spl-transfer-hook-interface.version = "0.5.0"
log = "0.4.27"
rand = "0.8.5"
base64.workspace = true
rayon = "1.10.0"
# keypair
rand_core = "0.6.4"
argon2 = "0.5.3"
aes-gcm = "0.10"
rpassword = "7.4.0"

[patch.crates-io]
# 强制所有依赖使用同一个 borsh 版本（如果兼容）
borsh = { version = "^1.5", features = ["derive"], package = "borsh" }
clap = { version = "4.5.37", features = ["derive", "env"] }

[[test]]
name = "test_pool_quote"
path = "tests/test_pool_quote.rs"
[[test]]
name = "test_clmm_sub"
path = "tests/test_clmm_sub.rs"
[[test]]
name = "test_clmm_sub_diff"
path = "tests/test_clmm_sub_diff.rs"
[[test]]
name = "test_amm_sub"
path = "tests/test_amm_sub.rs"
[[test]]
name = "test_pump_fun_sub"
path = "tests/test_pump_fun_sub.rs"
[[test]]
name = "test_dlmm_sub"
path = "tests/test_dlmm_sub.rs"
[[test]]
name = "test"
path = "tests/test.rs"

[dev-dependencies]
criterion = { version = "0.5", features = ["async_tokio", "html_reports"] }
serde-diff = "0.4"
flamegraph = "0.6.8"
tempfile = "3.19.1"

[[bench]]
name = "test_create_instruction"
harness = false
[[bench]]
name = "test_route_quote"
harness = false
[[bench]]
name = "test_hashmap"
harness = false
[[bench]]
name = "test_dashmap"
harness = false
[[bench]]
name = "test_build_graph"
harness = false

[profile.release]
opt-level = 3            # 最高优化
lto = "fat"              # 全程序链接时优化
codegen-units = 1        # 单线程生成代码，优化一致性
panic = "abort"          # panic 时直接终止，提高速度
incremental = false      # 禁用增量编译，确保完整优化
debug = false            # 禁用调试信息
strip = "symbols"        # 去除符号表，减小体积（需要 Rust 1.60


