[package]
name = "router"
version = "0.0.1"
edition = "2021"
license = "MIT"
authors = ["solana"]

[lib]
doctest = false

[dependencies]
borsh = "^1.5"
anchor-lang = { version = "0.29.0", features = ["derive"], package = "anchor-lang" }

serde.workspace = true
serde_json.workspace = true
bincode.workspace = true
dashmap = { workspace = true }
solana-program = { workspace = true }
solana-client = { workspace = true }
solana-sdk = { workspace = true }
spl-token-2022 = { workspace = true }
anyhow = { workspace = true }
base58.workspace = true
chrono.workspace = true
futures-util.workspace = true
spl-token = { workspace = true }

yellowstone-grpc-client = { workspace = true }
yellowstone-grpc-proto = { workspace = true }
solana-account-decoder = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing-appender = { workspace = true }
thiserror = "1.0.51"
num-traits = "0.2.19"
num-derive = "0.4.2"
bytemuck = { workspace = true, features = ["derive", "min_const_generics"] }
safe-transmute = "0.11.2"
burberry = { workspace = true }
eyre.workspace = true
async-stream = "0.3.6"
async-channel.workspace = true
moka.workspace = true
uint = { workspace = true }
anchor-spl = { workspace = true }
spl-associated-token-account.workspace = true
reqwest.workspace = true
arrayref = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }

num-integer = "0.1.45"
anchor-client.workspace = true
ruint.version = "1.3.0"
spl-transfer-hook-interface.version = "0.5.0"
log = "0.4.27"
rand = "0.8.5"
base64.workspace = true
[patch.crates-io]
# 强制所有依赖使用同一个 borsh 版本（如果兼容）
borsh = { version = "^1.5", features = ["derive"], package = "borsh" }


[[bench]]
name = "test_quote_benches"
harness = false

[[test]]
name = "test_pool_quote"
path = "tests/test_pool_quote.rs"
[[test]]
name = "test_clmm_sub"
path = "tests/test_clmm_sub.rs"
[[test]]
name = "test_clmm_sub_diff"
path = "tests/test_clmm_sub_diff.rs"
[[test]]
name = "test_amm_sub"
path = "tests/test_amm_sub.rs"
[[test]]
name = "test_pump_fun_sub"
path = "tests/test_pump_fun_sub.rs"
[[test]]
name = "test_dlmm_sub"
path = "tests/test_dlmm_sub.rs"

[dev-dependencies]
criterion = "0.5"
serde-diff = "0.4"


