[package]
name = "router"
version = "0.0.1"
edition = "2021"

[lib]
doctest = false

[dependencies]
dex = { path = "../../lib/dex", version = "0.0.1" }
raydium-amm = { path = "../../lib/raydium-amm", version = "0.0.1" }
raydium-clmm = { path = "../../lib/raydium-clmm", version = "0.0.1" }
pump-fun = { path = "../../lib/pump-fun", version = "0.0.1" }
solana-program = {workspace = true}
solana-client = { workspace = true }
spl-token-2022 = { workspace = true }
arrayref = { workspace = true }
log = "0.4"
env_logger = "0.10"
rayon = "1.10"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "test_quote_benches"
harness = false