[package]
name = "router"
version = "0.0.1"
edition = "2021"

[lib]
doctest = false

[dependencies]
dex = { path = "../../lib/dex", version = "0.0.1" }
raydium-amm = { path = "../../lib/raydium-amm", version = "0.0.1" }
raydium-clmm = { path = "../../lib/raydium-clmm", version = "0.0.1" }
pump-fun = { path = "../../lib/pump-fun", version = "0.0.1" }
meteora-dlmm = { path = "../../lib/meteora-dlmm", version = "0.0.1" }
solana-program = { workspace = true }
solana-client = { workspace = true }
solana-sdk = { workspace = true }
spl-token-2022 = { workspace = true }
arrayref = { workspace = true }
anyhow = { workspace = true }
tokio = { version = "1.44.1", features = ["rt", "rt-multi-thread", "macros"] }
base58 = "0.2.0"
chrono = "0.4"
futures-util = "0.3"
tonic = "0.12.1"
spl-token = { workspace = true }
bincode = "1.3.3"
anchor-spl = { workspace = true }
yellowstone-grpc-client = { workspace = true }
yellowstone-grpc-proto = { workspace = true }
solana-account-decoder = { workspace = true }
futures = "0.3.30"

tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing-appender = { workspace = true }

[dev-dependencies]
criterion = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde-diff = "0.4"
serde_json = "1.0"

[[bench]]
name = "test_quote_benches"
harness = false

[[test]]
name = "test_pool_quote"
path = "tests/test_pool_quote.rs"
[[test]]
name = "test_clmm_sub"
path = "tests/test_clmm_sub.rs"
[[test]]
name = "test_clmm_sub_diff"
path = "tests/test_clmm_sub_diff.rs"
[[test]]
name = "test_amm_sub"
path = "tests/test_amm_sub.rs"
[[test]]
name = "test_pump_fun_sub"
path = "tests/test_pump_fun_sub.rs"
[[test]]
name = "test_dlmm_sub"
path = "tests/test_dlmm_sub.rs"